DROP TABLE payments IF EXISTS;
DROP TABLE orderdetails IF EXISTS;
DROP TABLE orders IF EXISTS;
DROP TABLE customers IF EXISTS;
DROP TABLE employees IF EXISTS;
DROP TABLE products IF EXISTS;
DROP TABLE productlines IF EXISTS;
DROP TABLE offices IF EXISTS;

CREATE TABLE customers (
  customerNumber INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customerName varchar(50) NOT NULL,
  contactLastName varchar(50) NOT NULL,
  contactFirstName varchar(50) NOT NULL,
  phone varchar(50) NOT NULL,
  addressLine1 varchar(50) NOT NULL,
  addressLine2 varchar(50) DEFAULT NULL,
  city varchar(50) NOT NULL,
  state varchar(50) DEFAULT NULL,
  postalCode varchar(15) DEFAULT NULL,
  country varchar(50) NOT NULL,
  salesRepEmployeeNumber INTEGER DEFAULT NULL,
  creditLimit decimal(10,2) DEFAULT NULL
);

CREATE TABLE employees (
  employeeNumber INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lastName varchar(50) NOT NULL,
  firstName varchar(50) NOT NULL,
  extension varchar(10) NOT NULL,
  email varchar(100) NOT NULL,
  officeCode varchar(10) NOT NULL,
  reportsTo INTEGER DEFAULT NULL,
  jobTitle varchar(50) NOT NULL
);

CREATE TABLE offices (
  officeCode varchar(10) NOT NULL,
  city varchar(50) NOT NULL,
  phone varchar(50) NOT NULL,
  addressLine1 varchar(50) NOT NULL,
  addressLine2 varchar(50) DEFAULT NULL,
  state varchar(50) DEFAULT NULL,
  country varchar(50) NOT NULL,
  postalCode varchar(15) NOT NULL,
  territory varchar(10) NOT NULL,
  PRIMARY KEY (officeCode)
);

CREATE TABLE orders (
  orderNumber INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  orderDate date NOT NULL,
  requiredDate date NOT NULL,
  shippedDate date DEFAULT NULL,
  status varchar(15) NOT NULL,
  comments text,
  customerNumber INTEGER NOT NULL
);

CREATE TABLE orderdetails (
  orderNumber INTEGER NOT NULL,
  productCode varchar(15) NOT NULL,
  quantityOrdered INTEGER NOT NULL,
  priceEach decimal(10,2) NOT NULL,
  orderLineNumber smallint NOT NULL,
  PRIMARY KEY (orderNumber,productCode)
);

CREATE TABLE payments (
  customerNumber INTEGER NOT NULL,
  checkNumber varchar(50) NOT NULL,
  paymentDate date NOT NULL,
  amount decimal(10,2) NOT NULL,
  PRIMARY KEY (customerNumber,checkNumber)
);

CREATE TABLE productlines (
  productLine varchar(50) NOT NULL PRIMARY KEY,
  textDescription varchar(4000) DEFAULT NULL,
  htmlDescription mediumtext,
  image mediumblob
);

CREATE TABLE products (
  productCode varchar(15) NOT NULL PRIMARY KEY,
  productName varchar(70) NOT NULL,
  productLine varchar(50) NOT NULL,
  productScale varchar(10) NOT NULL,
  productVendor varchar(50) NOT NULL,
  productDescription text NOT NULL,
  quantityInStock smallint NOT NULL,
  buyPrice decimal(10,2) NOT NULL,
  MSRP decimal(10,2) NOT NULL
);

ALTER TABLE customers
ADD CONSTRAINT customers_ibfk_1 
FOREIGN KEY (salesRepEmployeeNumber) 
REFERENCES employees (employeeNumber);

ALTER TABLE employees
ADD CONSTRAINT employees_ibfk_1 
FOREIGN KEY (reportsTo) 
REFERENCES employees (employeeNumber);

ALTER TABLE employees
ADD CONSTRAINT employees_ibfk_2 
FOREIGN KEY (officeCode) 
REFERENCES offices (officeCode);

ALTER TABLE orderdetails
ADD CONSTRAINT orderdetails_ibfk_1 
FOREIGN KEY (orderNumber) 
REFERENCES orders (orderNumber);

ALTER TABLE orderdetails
ADD CONSTRAINT orderdetails_ibfk_2 
FOREIGN KEY (productCode) 
REFERENCES products (productCode);

ALTER TABLE orders
ADD CONSTRAINT orders_ibfk_1 
FOREIGN KEY (customerNumber)
REFERENCES customers (customerNumber);

ALTER TABLE payments
ADD CONSTRAINT payments_ibfk_1 
FOREIGN KEY (customerNumber) 
REFERENCES customers (customerNumber);

ALTER TABLE products
ADD CONSTRAINT products_ibfk_1 
FOREIGN KEY (productLine) 
REFERENCES productlines (productLine);